[collection]
# Sites to visit, should be in {category: [url, ...]} format
sites_in = "sites5000.json"
log_level = ""

[collection.db]
# MongoDB config
uri = "mongodb://127.0.0.1:27017"
name = "ephemerals"
collection = "sites"

[collection.browser]
# Path to Playwright browser (Chromium) binary IF LEFT EMPTY IT WILL BE DETECTED AUTOMATICALLY
path = ""
# How many tabs to be open at any given time
max_tabs = 64
# Timeout for waiting for "networkidle" in milliseconds
timeout = 30000

[collection.dns]
# resolv.conf format configuration for getting dns resolvers
conf_path = "/etc/resolv.conf"


[preprocess]
# List of URLs to be processed
input = "sites100k.json"
# Output of the URLs that 'exist'
exists_out = "100k_exists.json"
# Output of the URLs that don't 'exist'
unexists_out = "100k_unexists.json"
# Should the output be pretty-printed JSON
pretty = true
# How many requests to send at one time
concurrent_requests = 64
